### PR TITLE
BASE: nuke BinOpCollector

### LINKED ISSUE #239: Purge `BinOpCollector`
Less global states

### PR DESCRIPTION
**Pull request by tsao-chi**
fix #239

### CODE REVIEW

**Review by ice1000 — APPROVED** [review]
bors r+ and btw you forgot to reformat DefVar.java

**Comment by ice1000** [comment]
```
DistillerTest > nestedPi() FAILED
    org.opentest4j.AssertionFailedError: expected: <Pi (A : Type) -> A = X> but was: <Pi (A : Type) -> = A X>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
        at app//org.aya.core.DistillerTest.nestedPi(DistillerTest.java:94)
```

**Review by imkiva — COMMENTED** [review]
excellent work ~

**Pull request merged**
