### PR TITLE
WIP: Copy Covariance from Arend(

### PR DESCRIPTION
**Pull request by tsao-chi**
fix https://github.com/aya-prover/aya-dev/issues/849

### CODE REVIEW

**Comment by ice1000** [comment]
I still think the error message is not very helpful. Is there a way to show the exact expression that is problematic?

Ideally, I would appreciate an error message that can help you understand what's wrong in the type checker without debugging the source code of the compiler.

**Comment by tsao-chi** [comment]
> I still think the error message is not very helpful. Is there a way to show the exact expression that is problematic?
> 
> Ideally, I would appreciate an error message that can help you understand what's wrong in the type checker without debugging the source code of the compiler.

I think sourcepos of the ctor definition is enough for user to understand what's wrong in most cases

**Comment by ice1000** [comment]
> > I still think the error message is not very helpful. Is there a way to show the exact expression that is problematic?
> > 
> > Ideally, I would appreciate an error message that can help you understand what's wrong in the type checker without debugging the source code of the compiler.
> 
> I think sourcepos of the ctor definition is enough for user to understand what's wrong in most cases

What if there are 3 mutually recursive data types with each of them 2-10 constructors?

Aya is going to self host and the definition of Term will be inductive-inductively defined together with contexts and type formers. Every introduction and elimination rule is a constructor. This is a real-world example.

**Comment by tsao-chi** [comment]
> What if there are 3 mutually recursive data types with each of them 2-10 constructors?
> 

I think it still should be a very rare case to trigger an error and see a hardly understandable error message.




might implement more detailed error message in future prs

**Comment by ice1000** [comment]
> > What if there are 3 mutually recursive data types with each of them 2-10 constructors?
> > 
> 
> I think it still should be a very rare case to trigger an error and see a hardly understandable error message.
> 
> 
> 
> 
> might implement more detailed error message in future prs

It's exactly when the code gets complicated do people need to look at error messages. So, I would prefer higher quality ones.

**Comment by ice1000** [comment]
I think positivity with the presence of HITs will be more complex. See https://github.com/agda/agda/issues/6336

**Pull request closed without merging**
