### PR TITLE
Normalizer should re-commit lambda application

### PR DESCRIPTION
**Pull request by imkiva**
Workaround a mysterious normalizer bug discovered in #403

### CODE REVIEW

**Review by lunalunaa — APPROVED** [review]
Looks good to me.

**Comment by imkiva** [comment]
Steps to debug this problem:

1. Add breakpoint in `Literalte.java:126`
2. Add breakpoint in `TermView.java:35`
3. Set advanced breakpoint like this
image

4. debug `test.aya` (file contents follows)
<details>
<pre>
open data Nat | zero | suc Nat
open data List (A : Type) : Type
  | nil
  | infixr :< A (List A)
def overlap infixl + (a b : Nat) : Nat
  | zero, a => a
  | a, zero => a
  | suc a, b => suc (a + b)
  | a, suc b => suc (a + b)
def overlap infixr ++ {A : Type} (xs ys : List A) : List A
  | nil, ys => ys
  | xs, nil => xs
  | a :< xs, ys => a :< (xs ++ ys)
def join {A : Type} (l : List (List A)) : List A
  | nil => nil
  | xs :< xss => xs ++ join xss
def map {A B : Type} (f : A -> B) (l : List A) : List B
  | f, nil => nil
  | f, a :< l => f a :< map f l
def pure {A : Type} (x : A) : List A => x :< nil
def infix >>= {A B : Type} (l : List A) (f : A -> List B) : List B => join (map f l)

def t1 => pure zero >>= (\ a => pure (suc zero) >>= (\ b => pure (a + b)))

--| `t1`{mode=nf}
</pre>
</details>

Sorry for the inconvenience that I cannot find a simpler repro code 😢

**Comment by imkiva** [comment]
@imkiva 冰有空的话看看这个

**Comment by ice1000** [comment]
See `feizhu` branch

**Comment by imkiva** [comment]
superseded by #417

**Pull request closed without merging**
