### PR TITLE
Fold with types

### PR DESCRIPTION
**Pull request by imkiva**
as title

### CODE REVIEW

**Comment by imkiva** [comment]
bors merge

**Comment by imkiva** [comment]
bors cancel

**Comment by ice1000** [comment]
What's the intention?

**Comment by imkiva** [comment]
> What's the intention?

For unifying some code in LSP and SyntaxHighlight

**Comment by imkiva** [comment]
bors merge

**Review by ice1000 — APPROVED** [review]
bors r+

**Pull request merged**
