### PR TITLE
ci: really fix for Java 19

### PR DESCRIPTION
**Pull request by imkiva**
image

jlink 👿

### CODE REVIEW

**Comment by imkiva** [comment]
image

gradle 👿

**Comment by imkiva** [comment]
image

Why can't gradle find these JDKs?

**Comment by imkiva** [comment]
image

openjdk! 👿

**Comment by imkiva** [comment]
image

powershell! 👿

**Comment by imkiva** [comment]
There shouldn't be internal errors

**Comment by imkiva** [comment]
https://mail.openjdk.org/pipermail/compiler-dev/2022-September/020446.html

**Comment by imkiva** [comment]
https://github.com/beryx/badass-jlink-plugin/issues/219

**Comment by ice1000** [comment]
> image
> 
> powershell! 👿
> 
> help me 😭 😭 😭 😭 

gradlew build -Dopt=blah

**Comment by imkiva** [comment]
> > image
> > 
> > powershell! 👿
> > 
> > help me 😭 😭 😭 😭 
> 
> gradlew build -Dopt=blah

yeah, it was fixed by `echo '' >> ....`

**Review by ice1000 — APPROVED** [review]
bors r+

**Pull request merged**
