### PR TITLE
`Term` refactoring

### PR DESCRIPTION
**Pull request by wsx-ucb**

### CODE REVIEW

**Comment by wsx-ucb** [comment]
Not sure why `gradle-check` is failing.
Seems to pass on my machine.

**Review by ice1000 — COMMENTED** [review]
What's the two flake files?

**Comment by ice1000** [comment]
> Not sure why `gradle-check` is failing. Seems to pass on my machine.

It's fine

**Comment by ice1000** [comment]
Merge?

**Comment by wsx-ucb** [comment]
> What's the two flake files?

Those make it easier for Nix users to setup the necessary development dependencies on their systems.
Due to the way Nix manage packages, directly using the JDK downloaded by gradle does not seems to work.

**Comment by ice1000** [comment]
> > What's the two flake files?
> 
> Those make it easier for Nix users to setup the necessary development dependencies on their systems. Due to the way Nix manage packages, directly using the JDK downloaded by gradle does not seems to work.

@AliasQli

**Pull request merged**
