### PR TITLE
Some repl enhancements

### PR DESCRIPTION
**Pull request by ice1000**
image

Right now I'm using the hack that @ShreckYe uses to run commands, but it should be changed to an extensible framework later.

Complete two subtasks of #87.

### CODE REVIEW

**Comment by ice1000** [comment]
Empty input crashes the repl. I think this shouldn't happen @ShreckYe

**Comment by ice1000** [comment]
bors merge

**Comment by ShreckYe** [comment]
> Empty input crashes the repl. I think this shouldn't happen @ShreckYe

Is this fixed by this PR?

**Comment by ice1000** [comment]
@ShreckYe Yes

**Pull request merged**
