### PR TITLE
No more `private public open`

### LINKED ISSUE #690: Confusing scope control modifiers -- `private public open data`
According to our grammar, we support:

```aya
private public open data Nat
  | zero
  | suc Nat
```

which looks so confusing!

### PR DESCRIPTION
**Pull request by HoshinoTented**
I am trying to resolve #690 without writing garbage code.

### CODE REVIEW

**Comment by HoshinoTented** [comment]
For decl: we have only `private` and `open`, they can be placed with any order.
* `private` and `open`: private data and open locally
* `private`: private decl
* `open`: open and re-export

But for module and open command, we still use `public`

**Comment by ice1000** [comment]
Did you finished implementing the proposed feature?

**Review by ice1000 — APPROVED** [review]

**Comment by HoshinoTented** [comment]
> Did you finished implementing the proposed feature?

The tests may solve your questions. (I don't know what the proposed feature is :( )

**Review by imkiva — APPROVED** [review]
Thank you ~

**Comment by ice1000** [comment]
> Thank you ~

Merge?

**Comment by HoshinoTented** [comment]
Merge.
bors r+

**Pull request merged**
