### PR TITLE
Move primitive related states to `TyckState`

### PR DESCRIPTION
**Pull request by imkiva**
## Changes
- `normalize` of Terms now accept a `@NotNull TyckState` (it is `@Nullable` before), because it holds primitives.
- `PrimDef.Factory` is no longer a singleton, instead, it is created every time the compilation task was created. (except for LSP, where we only clear the primitive factory)

## Tasks
- [x] Get rid of global states
- [x] Update tests
- [x] Test these changes in LSP, make sure it does not break any LSP feature

### CODE REVIEW

**Comment by ice1000** [comment]
我靠

**Comment by imkiva** [comment]
> 我靠

what's going on?

**Comment by imkiva** [comment]
image

Yeah!! LSP w/ Library is still working!!!

**Comment by ice1000** [comment]
tql. Will review in a day

**Review by ice1000 — APPROVED** [review]
bors r=dark-flames

**Pull request merged**
