### PR TITLE
Bullet/Ordered List

### PR DESCRIPTION
**Pull request by HoshinoTented**
Solve #770

### CODE REVIEW

**Comment by ice1000** [comment]
I just merged a big branch, is there merge conflicts?

**Comment by HoshinoTented** [comment]
> I just merged a big branch, is there merge conflicts?

Solved

**Review by ice1000 — APPROVED** [review]
Cool. The goal is to merge this before @imkiva get up and update #794

**Review by ice1000 — APPROVED** [review]
bors merge

**Review by imkiva — COMMENTED** [review]
What is the point of `EnumSet<Outer>`

**Comment by ice1000** [comment]
> What is the point of `EnumSet<Outer>`

5f8595ebd329e5a3f9b78c1abe8b6142219a29c4

**Pull request merged**
