### PR TITLE
Library in REPL

### LINKED ISSUE #226: Load library in repl

### PR DESCRIPTION
**Pull request by imkiva**
This PR makes REPL load libraries by traversing all the sources of a library (including its dependencies) and manually importing their exported definitions (maybe all definitions for debugging purpose?) to the REPLContext.

close #226

### CODE REVIEW

**Comment by ice1000** [comment]
Can we now load a file and open a module in it?

**Comment by imkiva** [comment]
@ice1000 No

**Comment by ice1000** [comment]
@imkiva Is that difficult or are we just too lazy?

**Comment by imkiva** [comment]
@ice1000 sorry, we already did it

**Comment by ice1000** [comment]
@imkiva Ok, sorry for the delay
bors merge this plz

**Pull request merged**
