### PR TITLE
Libary Dependency Graph

### PR DESCRIPTION
**Pull request by HoshinoTented**
I hope these utils are helpful in solving #759.

TODO: do we really need those tests?

### CODE REVIEW

**Comment by HoshinoTented** [comment]
These utils work incorrectly with `DiskLibraryOwner`, cause the same library can have different `LibraryOwner` which are not `equals`.

How to check whether two LibraryOwner are equal? `LibraryOwner#underlyingLibrary().libraryRoot().equals`?

**Comment by ice1000** [comment]
Maybe we should create a dedicated field for that purpose...

**Comment by imkiva** [comment]
See the api note on LibraryOwner.

> * @apiNote DO NOT USE this class as Map key, use {@link #underlyingLibrary()} instead.

**Comment by HoshinoTented** [comment]
😱

**Review by ice1000 — APPROVED** [review]
bors r+

**Pull request merged**
