### PR TITLE
Normalizer should subst before normalizing

### PR DESCRIPTION
**Pull request by ice1000**
This should supersede #411 

/cc @imkiva @lunalunaa

### CODE REVIEW

**Review by imkiva — COMMENTED** [review]
There're `.view().subst().normalize` in other cases of `CallTerm.Hole`, `CallTerm.Fn`, `CallTerm.Access`. 

Are their subst need to be committed before normalizing?

**Comment by ice1000** [comment]
> There're `.view().subst().normalize` in other cases of `CallTerm.Hole`, `CallTerm.Fn`, `CallTerm.Access`. 
> 
> Are their subst need to be committed before normalizing?
> 
 
Yes I guess so

**Comment by ice1000** [comment]
> There're `.view().subst().normalize` in other cases of `CallTerm.Hole`, `CallTerm.Fn`, `CallTerm.Access`. 
> 
> Are their subst need to be committed before normalizing?
> 

Can you do it?

**Comment by imkiva** [comment]
> > There're `.view().subst().normalize` in other cases of `CallTerm.Hole`, `CallTerm.Fn`, `CallTerm.Access`. 
> > 
> > Are their subst need to be committed before normalizing?
> > 
> 
> Can you do it?

Sure. When I finish [this TODO](https://github.com/aya-prover/aya-dev/pull/404#discussion_r873616657)

**Comment by imkiva** [comment]
bors merge

**Pull request merged**
