### PR TITLE
NBE WIP

### PR DESCRIPTION
**Pull request by ice1000**

### CODE REVIEW

**Comment by ice1000** [comment]
有生之年系列

**Comment by SchrodingerZhu** [comment]
What is the plan on this?

**Comment by ice1000** [comment]
> What is the plan on this?

It's probably abandoned. We will need to switch to using a proper JIT compiler and use the current core language directly for closures.

**Comment by ice1000** [comment]
New HOAS! https://github.com/aya-prover/locally-nameless-aya-draft/pull/78

**Pull request closed without merging**
