### PR TITLE
LHS: add Lhs as type checked Pat

### PR DESCRIPTION
**Pull request by tonfeiz**
See #242.

There are some problems:
1. Many duplicate code with `Pat` in serialize and distiller process, but seems no better ways
2.  `PatCCTest` cannot be passed because we relied on `Pat` in `Def` to classify, but now we're using `Lhs`. I'm still thinking about better ways to deal with that. 
3. `PatMatcher` has been changed a lot(maybe not a lot, but the logic is kind of different than before anyway), so pay attention to this when reviewing.

I may add some comments or tests afterwards, but the overall code won't be changed a lot, so I just push them for now. I'm pretty sure there must be some(or many :rofl:) problems, just comment and I'll fix them.

### CODE REVIEW

**Comment by tonfeiz** [comment]
Another problem is `type` for `Lhs.Ctor` is saved because in `LhsToTerm` we need to generate a `CallTerm.Con`. It seems necessary.

**Review by ice1000 — CHANGES_REQUESTED** [review]
Branch out of date of main

**Comment by ice1000** [comment]
> 1. Many duplicate code with `Pat` in serialize and distiller process, but seems no better ways

Remove the serialization code for `Pat` plz.

> 2. `PatCCTest` cannot be passed because we relied on `Pat` in `Def` to classify, but now we're using `Lhs`. I'm still thinking about better ways to deal with that.

Yes, you forgot to replace the `Pat` in `Def` with `Lhs`.

> 3. `PatMatcher` has been changed a lot (maybe not a lot, but the logic is kind of different than before anyway), so pay attention to this when reviewing.

You forgot to deal with `RefTerm.MetaPat`.

> I may add some comments or tests afterwards, but the overall code won't be changed a lot, so I just push them for now. I'm pretty sure there must be some (or many 🤣) problems, just comment and I'll fix them.

I've pushed some, you may wanna take a look. Remember to rebase on latest main tho.

**Comment by tonfeiz** [comment]
> You forgot to deal with `RefTerm.MetaPat`.

No, I've dealt with that. However it's different than before. Just take a closer look at it.



> Yes, you forgot to replace the `Pat` in `Def` with `Lhs`.

That's not the problem here :rofl:. It's just because I've replaced `Pat`  with `Lhs` in `Def`, so we can't writing code like in `PatCCTest` anymore. `PatCCTest` is kind of like cheating, we first type checked some code, then we use the type checked `Pat` to classify. Now we are using `Lhs`, which prevents this kind of cheating, but also break the code and makes it really difficult to rewrite.

For your question, I know there are still `Pat` in `CtorDef`. However, it seems we can't replace it with `Lhs` because of #271. When we `selectCtor` in `PatTycker`, we'll use `Pat` in `CtorDef`, and perform the matching process, while at the same time we also expect to solve some `MetaPat`. If we change `Pat` to `Lhs`, then `MetaPat`'s solution might be an `Lhs`!

Another negative result of that is we cannot remove serialization code for `Pat` as it's still used in `CtorDef`.

To be honest, I'm kind of wondering is it really necessary to do the refactoring? I mean,  `MetaPat` is kind of blurring the boundary between `Lhs` and `Pat`. And refactoring is the reverse process, which adds some more subtleties.

**Comment by ice1000** [comment]
> No, I've dealt with that. However it's different than before. Just take a closer look at it.

😭

> `PatCCTest` is kind of like cheating, we first type checked some code, then we use the type checked `Pat` to classify. Now we are using `Lhs`, which prevents this kind of cheating, but also break the code and makes it really difficult to rewrite.

It tests the shape of the classification results. I guess you can delete it if it's annoying, as pattern classification is a rather stable feature (future refactoring won't change this part of the algorithm either).

> If we change `Pat` to `Lhs`, then `MetaPat`'s solution might be an `Lhs`!

Oh no, that's beyond my estimation! 😟 What about this: we remove `Pat::type` and `Pat.Tuple::type`, and make a function from `Lhs` to `Pat`?

> Another negative result of that is we cannot remove serialization code for `Pat` as it's still used in `CtorDef`.

Yes!! I really wanna kill that 😭

> To be honest, I'm kind of wondering is it really necessary to do the refactoring? I mean, `MetaPat` is kind of blurring the boundary between `Lhs` and `Pat`. And refactoring is the reverse process, which adds some more subtleties.

This can help us understand the code better. See? I wasn't aware of the fact that meta patteriable unification requires `Pat` instead of `Lhs`. I've learned from this work, tyvm!

**Comment by ice1000** [comment]
> Oh no, that's beyond my estimation! 😟 What about this: we remove `Pat::type` and `Pat.Tuple::type`, and make a function from `Lhs` to `Pat`?
> 
> >

I've done that in a recent commit: 61ab8803bcd3c691efd9d71f975e8db3dc271eb5

**Comment by ice1000** [comment]
Created #283

**Comment by tonfeiz** [comment]
> we remove `Pat::type` and `Pat.Tuple::type`, and make a function from `Lhs` to `Pat`?

That's OK. However, I should remind you that you're blurring the boundary furthurmore. Now they are interchangeable, and once we add something in `Pat`, we'll have to add the same thing in `Lhs`.

> I've done that in a recent commit: [61ab880](https://github.com/aya-prover/aya-dev/commit/61ab8803bcd3c691efd9d71f975e8db3dc271eb5)

You're too productive :rofl:. I can do the rest(add  `Pat`->`Lhs` and delete `SerPat` and more) later if you're not in a hurry.

**Comment by ice1000** [comment]
> That's OK. However, I should remind you that you're blurring the boundary furthurmore. Now they are interchangeable, and once we add something in `Pat`, we'll have to add the same thing in `Lhs`.

Yes, that's also what I see. Once we have JEP 420 merged, we may use a type tag for distinguishing `Pat` and `Lhs`:

+ `Keep : Tag`
+ `Pat<T extends Tag>`
+ `Ctor<T>(Seq<Pat<T>>) : Pat<T>` and similarly `Tuple`
+ `Bind : Pat<Keep>`
+ `Absurd : Pat<Tag>`
+ `MetaPat : Pat<Tag>`

Then, we can have two `Matching`s, one contains `Pat<Keep>` and one contains `Pat<Tag>` -- the latter may contain `Absurd` or `MetaPat` but the former can't.

**Comment by ice1000** [comment]
I propose closing this, as this is a negatively successful experiment (that we now know that something's impossible).

**Comment by tonfeiz** [comment]
> I propose closing this, as this is a negatively successful experiment (that we now know that something's impossible).

Sure. Just close it~

**Comment by ice1000** [comment]
Closed upon agreement

**Comment by ice1000** [comment]
For the record, the commit are still accessible via GitHub even I deleted the branch: 4de80a4b7fa9e2d8beda0d4a7fd543e8dc9b3816

https://github.com/aya-prover/aya-dev/commit/4de80a4b7fa9e2d8beda0d4a7fd543e8dc9b3816.patch

**Pull request closed without merging**
