### PR TITLE
Use html "class" attribute to set code style

### PR DESCRIPTION
**Pull request by imkiva**
It is now customizable by frontends!

### CODE REVIEW

**Review by ice1000 — APPROVED** [review]
bors merge

**Comment by ice1000** [comment]
Do you think HTML constants should go to some resource files?

**Comment by imkiva** [comment]
> Do you think HTML constants should go to some resource files?

I am not sure. Some constants refer to each other, so it may be hard (or make the usage code longer) to extract.

**Comment by ice1000** [comment]
> > Do you think HTML constants should go to some resource files?
> 
> I am not sure. Some constants refer to each other, so it may be hard (or make the usage code longer) to extract.

We can extract the basic ones

**Pull request merged**
