### PR TITLE
Enhance #646

### PR DESCRIPTION
**Pull request by HoshinoTented**
TODO:
- [x] import color scheme (also style family if possible) from the vscode color theme file

Refs:
[Sematic Highlight Guide](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide)
[Theme Color Table](https://code.visualstudio.com/api/references/theme-color)
[TextMate Grammar](https://macromates.com/manual/en/language_grammars)

### CODE REVIEW

**Comment by HoshinoTented** [comment]
We can delete the RenderOptionsObject if we can import the color scheme from vscode.

**Comment by HoshinoTented** [comment]
One problem is that the vscode color theme format is too flexible, Gson is unable to deserialize union type (or I don't know how to do it)

**Comment by HoshinoTented** [comment]
> One problem is that the vscode color theme format is too flexible, Gson is unable to deserialize union type (or I don't know how to do it)

I think I can impl one.

**Comment by HoshinoTented** [comment]
You can find the builtin vscode color themes at "\<VSCode\>/resources/app/extensions/theme-defaults/themes" (Windows)

**Comment by ice1000** [comment]
Wow cool!!

**Comment by HoshinoTented** [comment]
A new problem, the vscode color theme isn't a restricted JSON, it allows comments, a comma after the last element like `[ 1, 2, 3, ]`, and Gson is unable to parse these.

**Comment by HoshinoTented** [comment]
Do we need to copy the vscode color theme file when the user wants to import from it?

**Comment by HoshinoTented** [comment]
> A new problem, the vscode color theme isn't a strict JSON: It allows comments, a comma after the last element like `[ 1, 2, 3, ]`, and Gson is unable to parse them.

Umm, Gson looks able to parse them, but in a weird way.

**Comment by HoshinoTented** [comment]
> > A new problem, the vscode color theme isn't a strict JSON: It allows comments, a comma after the last element like `[ 1, 2, 3, ]`, and Gson is unable to parse them.
> 
> Umm, Gson looks able to parse them, but in a weird way.

Gson is able to parse `[ 1, 2, 3, ]`, but `{ "foo": "bar", "bar": "baz", }` isn't.

**Review by ice1000 — APPROVED** [review]
bors r=@ice1000 @HoshinoTented @imkiva

**Comment by ice1000** [comment]
image
All at once!!

**Pull request merged**
