### PR TITLE
ERROR: improve error report (#96)

### PR DESCRIPTION
**Pull request by imkiva**
- Add line break between each problem
- Count errors and warnings

Signed-off-by: imkiva <imkiva@islovely.icu>

### CODE REVIEW

**Comment by ice1000** [comment]
Also: maybe we should find a better way to maintain the test cases. Right now it's tracking all the details of the compiler output, and maybe we don't wanna do that.

**Comment by imkiva** [comment]
Does this mean _this catch clause is unreachable_?

image

**Comment by imkiva** [comment]
> Sometimes these are just inaccurate. Try setting a break point if you are really curious.

Breakpoint in `FileModuleLoader` does not hit after all tests are passed. I think we can remove these catch clauses because `SingleFileCompiler` also caught these exceptions whose breakpoint was hit.

**Comment by ice1000** [comment]
> btw, I decide to squash this PR since this feature is so simple

/cc https://github.com/bors-ng/bors-ng/issues/1028

**Pull request merged**
