### PR TITLE
Update bors message, upgrade guest

### PR DESCRIPTION
**Pull request by ice1000**
bors r+

/cc @lunalunaa the function you need is `CofThy.isOne`

### CODE REVIEW

**Comment by imkiva** [comment]
Should bors respect commit check as well?

**Comment by ice1000** [comment]
@imkiva I agree

**Comment by lunalunaa** [comment]
I wonder why it has this name though

> bors r+
> 
> /cc @lunalunaa the function you need is `CofThy.isOne`

**Comment by ice1000** [comment]
@lunalunaa > I wonder why it has this name though 

It's a reference to Cubical Agda's IsOne

**Pull request merged**
