### PR TITLE
Globular type theory

### PR DESCRIPTION
**Pull request by hgouni**

### CODE REVIEW

**Comment by ice1000** [comment]
CI failed

**Comment by ice1000** [comment]
It's a breaking change

**Comment by hgouni** [comment]
Irrelevant under globular type theory, it's a new paradigm.

**Comment by hgouni** [comment]
Wow, code coverage is soooo good

**Comment by hgouni** [comment]
We agreed to make this a repl command. This PR will be updated to reflect that.

**Comment by hgouni** [comment]
Saltaya

**Comment by ice1000** [comment]
🧂

**Pull request closed without merging**
