### PR TITLE
No More Duplicated Vars

### PR DESCRIPTION
**Pull request by HoshinoTented**
There are some problems because of the duplicated vars, why don't we just add an assertion and save our time?

### CODE REVIEW

**Comment by HoshinoTented** [comment]
Maybe we should solve all the duplicated vars problems and then merge this...

**Comment by ice1000** [comment]
I just realized something. You have GlobalConfig and tests will enable it

**Comment by ice1000** [comment]
I have a lot of other tests/sanity checks that I want to add. I believe we should have a general mechanism for that.

Maybe tracing should be part of this config

**Comment by ice1000** [comment]
There are already some limited scope checks. There can be more.

**Comment by ice1000** [comment]
I have fixed some problems caused by duplicated vars. There are more, but I would love to merge these changes and have another PR that enables the assertion back and we'll see what we can do in the future.

What do you think? @HoshinoTented

**Comment by ice1000** [comment]
bors r+

Tests passed locally.

**Comment by ice1000** [comment]
What I've done locally:

```diff
diff --git a/base/src/main/java/org/aya/tyck/StmtTycker.java b/base/src/main/java/org/aya/tyck/StmtTycker.java
index 4010646a4..8fc19b804 100644
--- a/base/src/main/java/org/aya/tyck/StmtTycker.java
+++ b/base/src/main/java/org/aya/tyck/StmtTycker.java
@@ -108,34 +108,39 @@ public final class StmtTycker extends TracedTycker {
       case TeleDecl.DataDecl decl -> {
         var signature = decl.signature;
         assert signature != null;
-        var body = decl.body.map(clause -> (CtorDef) tyck(clause, tycker));
+        var body = decl.body.map(clause -> traced(clause, tycker, this::checkCtor));
         yield new DataDef(decl.ref, signature.param(), signature.result(), body);
       }
       case TeleDecl.PrimDecl decl -> decl.ref.core;
       case TeleDecl.StructDecl decl -> {
         var signature = decl.signature;
         assert signature != null;
-        var body = decl.fields.map(field -> (FieldDef) tyck(field, tycker));
+        var body = decl.fields.map(field -> traced(field, tycker, (f, e) ->
+          checkField(f, e, false)));
         yield new StructDef(decl.ref, signature.param(), signature.result(), body);
       }
       // Do nothing, data constructors is just a header.
       case TeleDecl.DataCtor ctor -> ctor.ref.core;
-      case TeleDecl.StructField field -> {
-        // TODO[ice]: remove this hack
-        if (field.ref.core != null) yield field.ref.core;
-        var signature = field.signature;
-        assert signature != null; // already handled in the entrance of this method
-        var structRef = field.structRef;
-        var structSig = structRef.concrete.signature;
-        assert structSig != null;
-        loadTele(tycker, structSig);
-        var result = signature.result();
-        var body = field.body.map(e -> tycker.inherit(e, result).wellTyped());
-        yield new FieldDef(structRef, field.ref, structSig.param(), signature.param(), result, body, field.coerce);
-      }
+      case TeleDecl.StructField field -> checkField(field, tycker, true);
     };
   }

+  private @NotNull FieldDef checkField(TeleDecl.StructField field, @NotNull ExprTycker tycker, boolean load) {
+    // TODO[ice]: remove this hack
+    if (field.ref.core != null) return field.ref.core;
+    var structRef = field.structRef;
+    var structSig = structRef.concrete.signature;
+    assert structSig != null;
+    // tyckHeader implies loadTele
+    if (field.signature == null) tyckHeader(field, tycker);
+    else if (load) loadTele(tycker, structSig);
+    var signature = field.signature;
+    assert signature != null;
+    var result = signature.result();
+    var body = field.body.map(e -> tycker.inherit(e, result).wellTyped());
+    return new FieldDef(structRef, field.ref, structSig.param(), signature.param(), result, body, field.coerce);
+  }
+
   // Apply a simple checking strategy for maximal metavar inference.
   public @NotNull FnDef simpleFn(@NotNull ExprTycker tycker, TeleDecl.FnDecl fn) {
     return traced(fn, tycker, this::doSimpleFn);
@@ -223,7 +228,7 @@ public final class StmtTycker extends TracedTycker {
         tycker.solveMetas();
         tycker.ctx = new SeqLocalCtx();
       }
-      case TeleDecl.DataCtor ctor -> checkCtor(tycker, ctor);
+      case TeleDecl.DataCtor ctor -> checkCtor(ctor, tycker);
       case TeleDecl.StructField field -> {
         if (field.signature != null) break;
         var structRef = field.structRef;
@@ -239,9 +244,13 @@ public final class StmtTycker extends TracedTycker {
     tracing(TreeBuilder::reduce);
   }

-  /** Extracted for the extreme complexity. */
-  private void checkCtor(@NotNull ExprTycker tycker, TeleDecl.DataCtor ctor) {
-    if (ctor.ref.core != null) return;
+  /**
+   * Extracted for the extreme complexity.
+   *
+   * @return
+   */
+  private @NotNull CtorDef checkCtor(TeleDecl.DataCtor ctor, @NotNull ExprTycker tycker) {
+    if (ctor.ref.core != null) return ctor.ref.core;
     var dataRef = ctor.dataRef;
     var dataConcrete = dataRef.concrete;
     var dataSig = dataConcrete.signature;
@@ -305,7 +314,9 @@ public final class StmtTycker extends TracedTycker {
       reporter.report(new CubicalError.PathConDominateError(ctor.clauses.sourcePos()));
       elabClauses = PartialTerm.DUMMY_SPLIT;
     }
-    dataConcrete.checkedBody.append(new CtorDef(dataRef, ctor.ref, pat, patternTele, tele, split, dataCall, ctor.coerce));
+    var def = new CtorDef(dataRef, ctor.ref, pat, patternTele, tele, split, dataCall, ctor.coerce);
+    dataConcrete.checkedBody.append(def);
+    return def;
   }

   private static void loadTele(@NotNull ExprTycker tycker, Def.Signature<?> dataSig) {
```

**Review by ice1000 — COMMENTED** [review]
perfect!

**Pull request merged**
