### PR TITLE
Generic FormTerm.Univ check, able to solve a lifted meta

### PR DESCRIPTION
**Pull request by tsao-chi**
This might be one possible solution to https://github.com/aya-prover/aya-dev/issues/448

### CODE REVIEW

**Comment by ice1000** [comment]
I think this solution has a problem. Let's say we have a hole, and we compare it with unknown level. This gives us core term with unknown levels.



If I'm not wrong on assuming unknown level represents "infinity level", this can generate a Girard paradox

**Comment by ice1000** [comment]
I think this solution has a problem. Let's say we have a hole, and we compare it with unknown level. This gives us core term with unknown levels.



If I'm not wrong on assuming unknown level represents "infinity level", this can generate a Girard paradox

**Comment by ice1000** [comment]
But unknown levels are going to be in the core, am I right?

**Comment by tsao-chi** [comment]
> But unknown levels are going to be in the core, am I right?

This should be prevented

**Comment by ice1000** [comment]
> > But unknown levels are going to be in the core, am I right?
> 
> This should be prevented

I think we should prevent using invalid core term for the sake of type checking.

We are inevitably going to have a isType function when we introduce more universes.

**Comment by tsao-chi** [comment]
> I think we should prevent using invalid core term for the sake of type checking.

I think it may be fine if it is invisible to users and other parts of aya

**Comment by ice1000** [comment]
> > I think we should prevent using invalid core term for the sake of type checking.
> 
> I think it may be fine if it is invisible to users and other parts of aya

But it's visible to type checking, and I think it's dangerous (while having a separate function for checking types is easy and harmless and not so much more difficult and is going to be done anyway).

You may solve metas to a unknown level, this can be an intermediate term used in type checking that does not get into the results, and this can make the results invalid.

Also, this is going to be very difficult to reimplement Aya in Aya in the future because we need to deal with unknown levels everywhere, like in serialization or something.

Most importantly, when we introduce more universes, this hack will become completely unnecessary :)

**Comment by ice1000** [comment]
I'll create a new issue for you and you'll see why a separate function is necessary

**Comment by ice1000** [comment]
Also, how is this related to lifted meta?

**Comment by ice1000** [comment]
> I'll create a new issue for you and you'll see why a separate function is necessary

#469

**Comment by tsao-chi** [comment]
Closing this hack

**Comment by ice1000** [comment]
Are you implementing #469?

**Comment by tsao-chi** [comment]
@ice1000 I will implement #448 first

**Pull request closed without merging**
