### PR TITLE
Merge: declModifiers + fnModifiers

### PR DESCRIPTION
**Pull request by HoshinoTented**

### CODE REVIEW

**Comment by HoshinoTented** [comment]
The parser is unavailable for now. Code `opaque def foo : Unit => unit` failed with a parser error which I don't understand.
Also, `def opaque foo : Unit => unit` produces `ERROR_ELEMENT` s in the AST tree, but Aya doesn't report them,

**Comment by ice1000** [comment]
Could you please try merging main

**Comment by ice1000** [comment]
image

**Comment by ice1000** [comment]
image
8 错

**Review by ice1000 — APPROVED** [review]

**Pull request merged**
