### PR TITLE
REPL enhancement

### LINKED ISSUE #382: NPE triggered because REPL context not cleaned up after tycking error
To trigger this bug in REPL, type `data Nat =`, followed by `Nat`.

The context is not properly cleaned up after catching exception. This causes `Nat` in the next line of input to be resolved into a `Def`.

https://github.com/aya-prover/aya-dev/blob/5e56d11bfde25b7fb3c0bb2cad592b24bbf1958c/cli/src/main/java/org/aya/cli/repl/ReplCompiler.java#L143-L145

### LINKED ISSUE #393: Parser error should not print stack trace in REPL
As titled

image

### PR DESCRIPTION
**Pull request by imkiva**
Fixes #382 fix #393

### CODE REVIEW

**Review by ice1000 — APPROVED** [review]
Maybe test the behavior?

**Review by ice1000 — APPROVED** [review]
bors d=imkiva

**Comment by imkiva** [comment]
bors d=lunalunaa

**Comment by ice1000** [comment]
IMO it's good enough. I would simply
bors r+

**Pull request merged**
