### PR TITLE
Rework publishing and versioning

### PR DESCRIPTION
**Pull request by imkiva**
Maybe we should let Actions publishing snapshot automatically

### CODE REVIEW

**Review by ice1000 — COMMENTED** [review]
Does SNAPSHOTs get automatically closed and released on maven central? Do you have to do anything on sonatype manually?

**Comment by imkiva** [comment]
> Does SNAPSHOTs get automatically closed and released on maven central? 

Snapshot repos [are not synced to Central](https://central.sonatype.org/publish/publish-maven/#performing-a-snapshot-deployment). And what do you mean by "close"? I didn't find related docs in the link above. 😢 

> Do you have to do anything on sonatype manually?

I will give a test locally. I am opening this PR early to let others check if these changes may break anything existing.

**Comment by ice1000** [comment]
> > Does SNAPSHOTs get automatically closed and released on maven central? 
> 
> Snapshot repos [are not synced to Central](https://central.sonatype.org/publish/publish-maven/#performing-a-snapshot-deployment). And what do you mean by "close"? I didn't find related docs in the link above. 😢 
> 
> > Do you have to do anything on sonatype manually?
> 
> I will give a test locally. I am opening this PR early to let others check if these changes may break anything existing.

For releases, running gradle publish doesn't publish things on maven central. Instead, it only uploads to sonatype, and you'll have to press some buttons on sonatype to publish

**Comment by ice1000** [comment]
The buttons you click are close and release

**Comment by imkiva** [comment]
> > > Does SNAPSHOTs get automatically closed and released on maven central?
> > 
> > 
> > Snapshot repos [are not synced to Central](https://central.sonatype.org/publish/publish-maven/#performing-a-snapshot-deployment). And what do you mean by "close"? I didn't find related docs in the link above. 😢
> > > Do you have to do anything on sonatype manually?
> > 
> > 
> > I will give a test locally. I am opening this PR early to let others check if these changes may break anything existing.
> 
> For releases, running gradle publish doesn't publish things on maven central. Instead, it only uploads to sonatype, and you'll have to press some buttons on sonatype to publish

Thank you for the explanation! Then the answer is no. Snapshot builds can only be used if:

> If you wish your users to consume your SNAPSHOT versions, they would need to add the snapshot repository to their Nexus Repository Manager, settings.xml, or pom.xml. Successfully deployed SNAPSHOT versions will be found in https://s01.oss.sonatype.org/content/repositories/snapshots/

**Comment by imkiva** [comment]
https://s01.oss.sonatype.org/content/repositories/snapshots/org/aya-prover/base/

**Comment by imkiva** [comment]
bors merge

**Pull request merged**
