### PR TITLE
A great crusade against error reporting and `ExprTycker` code reorganization

### PR DESCRIPTION
**Pull request by ice1000**
This PR:

+ Simplify conquer unfolding.
+ Tries to fix the GraalVM build problem.
+ Introduces a uniform way to generate friendly error message on unification failures.
+ Dissolve `ExprTycker` into several sealed, abstract classes with dedicated methods, so `ExprTycker` itself is now less complicated.

### CODE REVIEW

**Comment by ice1000** [comment]
image
This is a big win.

**Comment by tsao-chi** [comment]
bors d=ice1000

**Comment by ice1000** [comment]
bors merge

**Comment by ice1000** [comment]
ExprTycker 苏 联 解 体

**Pull request merged**
