### PR TITLE
Unification of many things

### PR DESCRIPTION
**Pull request by ice1000**
bors r+

### CODE REVIEW

**Comment by ice1000** [comment]
bors merge

**Comment by ice1000** [comment]
bors cancel

**Comment by imkiva** [comment]
bors merge

**Comment by imkiva** [comment]
image
????

image

**Review by ice1000 — COMMENTED** [review]
bors merge?

**Comment by imkiva** [comment]
Yes. 
bors merge

**Comment by ice1000** [comment]
> image
> ????
> 
> image
> 

Just rerun. It should be fine.

Testing this can help us track GitHub API changes

**Pull request merged**
