### PR TITLE
sort: use single record instead of interface

### PR DESCRIPTION
**Pull request by tsao-chi**

### CODE REVIEW

**Comment by tsao-chi** [comment]
I used wrong main

**Comment by ice1000** [comment]
Try again

**Comment by tsao-chi** [comment]
qwq

**Comment by ice1000** [comment]
Tai can le

**Comment by tsao-chi** [comment]
What’s this

> Tai can le

**Comment by ice1000** [comment]
> What’s this
> 
> > Tai can le
> 
> 

It's pinyin

**Pull request closed without merging**
